DROP TABLE IF EXISTS "Product";
DROP TABLE IF EXISTS "Store";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "Store" (
    "Id" UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    "Name" VARCHAR(255) NOT NULL,
    "Address" VARCHAR(255) NOT NULL,
	"PhoneNumber" VARCHAR(10) NOT NULL,
	"IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
	"DateCreated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"DateUpdated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"CreatedByUserId" INT NOT NULL,
	"UpdatedByUserId" INT NOT NULL
);

CREATE TABLE "Product" (
    "Id" UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
	"StoreId" UUID,
    "Name" VARCHAR(255) NOT NULL,
    "Price" NUMERIC (4,2) NOT NULL,
	"ExpirationDate" DATE NOT NULL,
	"IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
	"DateCreated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"DateUpdated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"CreatedByUserId" INT NOT NULL,
	"UpdatedByUserId" INT NOT NULL,
    CONSTRAINT "FK_Product_Store_StoreId" 
		FOREIGN KEY ("StoreId") 
		REFERENCES "Store"("Id")
);

